package tk.mybatis.springboot.model;

import java.util.Date;

public class BfProcessInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bf_process_info.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bf_process_info.biz_key
     *
     * @mbggenerated
     */
    private String bizKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bf_process_info.biz_serial
     *
     * @mbggenerated
     */
    private String bizSerial;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bf_process_info.exec_status
     *
     * @mbggenerated
     */
    private String execStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bf_process_info.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bf_process_info.bean_name
     *
     * @mbggenerated
     */
    private String beanName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bf_process_info.facts
     *
     * @mbggenerated
     */
    private String facts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bf_process_info.param
     *
     * @mbggenerated
     */
    private String param;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bf_process_info.node
     *
     * @mbggenerated
     */
    private String node;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bf_process_info.order_number
     *
     * @mbggenerated
     */
    private Integer orderNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bf_process_info.handled_times
     *
     * @mbggenerated
     */
    private Integer handledTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bf_process_info.last_handle_msg
     *
     * @mbggenerated
     */
    private String lastHandleMsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bf_process_info.created_at
     *
     * @mbggenerated
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bf_process_info.updated_at
     *
     * @mbggenerated
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bf_process_info.id
     *
     * @return the value of bf_process_info.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bf_process_info.id
     *
     * @param id the value for bf_process_info.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bf_process_info.biz_key
     *
     * @return the value of bf_process_info.biz_key
     *
     * @mbggenerated
     */
    public String getBizKey() {
        return bizKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bf_process_info.biz_key
     *
     * @param bizKey the value for bf_process_info.biz_key
     *
     * @mbggenerated
     */
    public void setBizKey(String bizKey) {
        this.bizKey = bizKey == null ? null : bizKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bf_process_info.biz_serial
     *
     * @return the value of bf_process_info.biz_serial
     *
     * @mbggenerated
     */
    public String getBizSerial() {
        return bizSerial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bf_process_info.biz_serial
     *
     * @param bizSerial the value for bf_process_info.biz_serial
     *
     * @mbggenerated
     */
    public void setBizSerial(String bizSerial) {
        this.bizSerial = bizSerial == null ? null : bizSerial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bf_process_info.exec_status
     *
     * @return the value of bf_process_info.exec_status
     *
     * @mbggenerated
     */
    public String getExecStatus() {
        return execStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bf_process_info.exec_status
     *
     * @param execStatus the value for bf_process_info.exec_status
     *
     * @mbggenerated
     */
    public void setExecStatus(String execStatus) {
        this.execStatus = execStatus == null ? null : execStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bf_process_info.name
     *
     * @return the value of bf_process_info.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bf_process_info.name
     *
     * @param name the value for bf_process_info.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bf_process_info.bean_name
     *
     * @return the value of bf_process_info.bean_name
     *
     * @mbggenerated
     */
    public String getBeanName() {
        return beanName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bf_process_info.bean_name
     *
     * @param beanName the value for bf_process_info.bean_name
     *
     * @mbggenerated
     */
    public void setBeanName(String beanName) {
        this.beanName = beanName == null ? null : beanName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bf_process_info.facts
     *
     * @return the value of bf_process_info.facts
     *
     * @mbggenerated
     */
    public String getFacts() {
        return facts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bf_process_info.facts
     *
     * @param facts the value for bf_process_info.facts
     *
     * @mbggenerated
     */
    public void setFacts(String facts) {
        this.facts = facts == null ? null : facts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bf_process_info.param
     *
     * @return the value of bf_process_info.param
     *
     * @mbggenerated
     */
    public String getParam() {
        return param;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bf_process_info.param
     *
     * @param param the value for bf_process_info.param
     *
     * @mbggenerated
     */
    public void setParam(String param) {
        this.param = param == null ? null : param.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bf_process_info.node
     *
     * @return the value of bf_process_info.node
     *
     * @mbggenerated
     */
    public String getNode() {
        return node;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bf_process_info.node
     *
     * @param node the value for bf_process_info.node
     *
     * @mbggenerated
     */
    public void setNode(String node) {
        this.node = node == null ? null : node.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bf_process_info.order_number
     *
     * @return the value of bf_process_info.order_number
     *
     * @mbggenerated
     */
    public Integer getOrderNumber() {
        return orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bf_process_info.order_number
     *
     * @param orderNumber the value for bf_process_info.order_number
     *
     * @mbggenerated
     */
    public void setOrderNumber(Integer orderNumber) {
        this.orderNumber = orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bf_process_info.handled_times
     *
     * @return the value of bf_process_info.handled_times
     *
     * @mbggenerated
     */
    public Integer getHandledTimes() {
        return handledTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bf_process_info.handled_times
     *
     * @param handledTimes the value for bf_process_info.handled_times
     *
     * @mbggenerated
     */
    public void setHandledTimes(Integer handledTimes) {
        this.handledTimes = handledTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bf_process_info.last_handle_msg
     *
     * @return the value of bf_process_info.last_handle_msg
     *
     * @mbggenerated
     */
    public String getLastHandleMsg() {
        return lastHandleMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bf_process_info.last_handle_msg
     *
     * @param lastHandleMsg the value for bf_process_info.last_handle_msg
     *
     * @mbggenerated
     */
    public void setLastHandleMsg(String lastHandleMsg) {
        this.lastHandleMsg = lastHandleMsg == null ? null : lastHandleMsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bf_process_info.created_at
     *
     * @return the value of bf_process_info.created_at
     *
     * @mbggenerated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bf_process_info.created_at
     *
     * @param createdAt the value for bf_process_info.created_at
     *
     * @mbggenerated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bf_process_info.updated_at
     *
     * @return the value of bf_process_info.updated_at
     *
     * @mbggenerated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bf_process_info.updated_at
     *
     * @param updatedAt the value for bf_process_info.updated_at
     *
     * @mbggenerated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}