package tk.mybatis.springboot.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class BfProcessInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bf_process_info
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bf_process_info
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bf_process_info
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bf_process_info
     *
     * @mbggenerated
     */
    public BfProcessInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bf_process_info
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bf_process_info
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bf_process_info
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bf_process_info
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bf_process_info
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bf_process_info
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bf_process_info
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bf_process_info
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bf_process_info
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bf_process_info
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bf_process_info
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("`id` is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("`id` is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("`id` =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("`id` <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("`id` >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("`id` >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("`id` <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("`id` <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("`id` in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("`id` not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("`id` between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("`id` not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andBizKeyIsNull() {
            addCriterion("`biz_key` is null");
            return (Criteria) this;
        }

        public Criteria andBizKeyIsNotNull() {
            addCriterion("`biz_key` is not null");
            return (Criteria) this;
        }

        public Criteria andBizKeyEqualTo(String value) {
            addCriterion("`biz_key` =", value, "bizKey");
            return (Criteria) this;
        }

        public Criteria andBizKeyNotEqualTo(String value) {
            addCriterion("`biz_key` <>", value, "bizKey");
            return (Criteria) this;
        }

        public Criteria andBizKeyGreaterThan(String value) {
            addCriterion("`biz_key` >", value, "bizKey");
            return (Criteria) this;
        }

        public Criteria andBizKeyGreaterThanOrEqualTo(String value) {
            addCriterion("`biz_key` >=", value, "bizKey");
            return (Criteria) this;
        }

        public Criteria andBizKeyLessThan(String value) {
            addCriterion("`biz_key` <", value, "bizKey");
            return (Criteria) this;
        }

        public Criteria andBizKeyLessThanOrEqualTo(String value) {
            addCriterion("`biz_key` <=", value, "bizKey");
            return (Criteria) this;
        }

        public Criteria andBizKeyLike(String value) {
            addCriterion("`biz_key` like", value, "bizKey");
            return (Criteria) this;
        }

        public Criteria andBizKeyNotLike(String value) {
            addCriterion("`biz_key` not like", value, "bizKey");
            return (Criteria) this;
        }

        public Criteria andBizKeyIn(List<String> values) {
            addCriterion("`biz_key` in", values, "bizKey");
            return (Criteria) this;
        }

        public Criteria andBizKeyNotIn(List<String> values) {
            addCriterion("`biz_key` not in", values, "bizKey");
            return (Criteria) this;
        }

        public Criteria andBizKeyBetween(String value1, String value2) {
            addCriterion("`biz_key` between", value1, value2, "bizKey");
            return (Criteria) this;
        }

        public Criteria andBizKeyNotBetween(String value1, String value2) {
            addCriterion("`biz_key` not between", value1, value2, "bizKey");
            return (Criteria) this;
        }

        public Criteria andBizSerialIsNull() {
            addCriterion("`biz_serial` is null");
            return (Criteria) this;
        }

        public Criteria andBizSerialIsNotNull() {
            addCriterion("`biz_serial` is not null");
            return (Criteria) this;
        }

        public Criteria andBizSerialEqualTo(String value) {
            addCriterion("`biz_serial` =", value, "bizSerial");
            return (Criteria) this;
        }

        public Criteria andBizSerialNotEqualTo(String value) {
            addCriterion("`biz_serial` <>", value, "bizSerial");
            return (Criteria) this;
        }

        public Criteria andBizSerialGreaterThan(String value) {
            addCriterion("`biz_serial` >", value, "bizSerial");
            return (Criteria) this;
        }

        public Criteria andBizSerialGreaterThanOrEqualTo(String value) {
            addCriterion("`biz_serial` >=", value, "bizSerial");
            return (Criteria) this;
        }

        public Criteria andBizSerialLessThan(String value) {
            addCriterion("`biz_serial` <", value, "bizSerial");
            return (Criteria) this;
        }

        public Criteria andBizSerialLessThanOrEqualTo(String value) {
            addCriterion("`biz_serial` <=", value, "bizSerial");
            return (Criteria) this;
        }

        public Criteria andBizSerialLike(String value) {
            addCriterion("`biz_serial` like", value, "bizSerial");
            return (Criteria) this;
        }

        public Criteria andBizSerialNotLike(String value) {
            addCriterion("`biz_serial` not like", value, "bizSerial");
            return (Criteria) this;
        }

        public Criteria andBizSerialIn(List<String> values) {
            addCriterion("`biz_serial` in", values, "bizSerial");
            return (Criteria) this;
        }

        public Criteria andBizSerialNotIn(List<String> values) {
            addCriterion("`biz_serial` not in", values, "bizSerial");
            return (Criteria) this;
        }

        public Criteria andBizSerialBetween(String value1, String value2) {
            addCriterion("`biz_serial` between", value1, value2, "bizSerial");
            return (Criteria) this;
        }

        public Criteria andBizSerialNotBetween(String value1, String value2) {
            addCriterion("`biz_serial` not between", value1, value2, "bizSerial");
            return (Criteria) this;
        }

        public Criteria andExecStatusIsNull() {
            addCriterion("`exec_status` is null");
            return (Criteria) this;
        }

        public Criteria andExecStatusIsNotNull() {
            addCriterion("`exec_status` is not null");
            return (Criteria) this;
        }

        public Criteria andExecStatusEqualTo(String value) {
            addCriterion("`exec_status` =", value, "execStatus");
            return (Criteria) this;
        }

        public Criteria andExecStatusNotEqualTo(String value) {
            addCriterion("`exec_status` <>", value, "execStatus");
            return (Criteria) this;
        }

        public Criteria andExecStatusGreaterThan(String value) {
            addCriterion("`exec_status` >", value, "execStatus");
            return (Criteria) this;
        }

        public Criteria andExecStatusGreaterThanOrEqualTo(String value) {
            addCriterion("`exec_status` >=", value, "execStatus");
            return (Criteria) this;
        }

        public Criteria andExecStatusLessThan(String value) {
            addCriterion("`exec_status` <", value, "execStatus");
            return (Criteria) this;
        }

        public Criteria andExecStatusLessThanOrEqualTo(String value) {
            addCriterion("`exec_status` <=", value, "execStatus");
            return (Criteria) this;
        }

        public Criteria andExecStatusLike(String value) {
            addCriterion("`exec_status` like", value, "execStatus");
            return (Criteria) this;
        }

        public Criteria andExecStatusNotLike(String value) {
            addCriterion("`exec_status` not like", value, "execStatus");
            return (Criteria) this;
        }

        public Criteria andExecStatusIn(List<String> values) {
            addCriterion("`exec_status` in", values, "execStatus");
            return (Criteria) this;
        }

        public Criteria andExecStatusNotIn(List<String> values) {
            addCriterion("`exec_status` not in", values, "execStatus");
            return (Criteria) this;
        }

        public Criteria andExecStatusBetween(String value1, String value2) {
            addCriterion("`exec_status` between", value1, value2, "execStatus");
            return (Criteria) this;
        }

        public Criteria andExecStatusNotBetween(String value1, String value2) {
            addCriterion("`exec_status` not between", value1, value2, "execStatus");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("`name` is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("`name` is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("`name` =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("`name` <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("`name` >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("`name` >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("`name` <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("`name` <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("`name` like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("`name` not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("`name` in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("`name` not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("`name` between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("`name` not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andBeanNameIsNull() {
            addCriterion("`bean_name` is null");
            return (Criteria) this;
        }

        public Criteria andBeanNameIsNotNull() {
            addCriterion("`bean_name` is not null");
            return (Criteria) this;
        }

        public Criteria andBeanNameEqualTo(String value) {
            addCriterion("`bean_name` =", value, "beanName");
            return (Criteria) this;
        }

        public Criteria andBeanNameNotEqualTo(String value) {
            addCriterion("`bean_name` <>", value, "beanName");
            return (Criteria) this;
        }

        public Criteria andBeanNameGreaterThan(String value) {
            addCriterion("`bean_name` >", value, "beanName");
            return (Criteria) this;
        }

        public Criteria andBeanNameGreaterThanOrEqualTo(String value) {
            addCriterion("`bean_name` >=", value, "beanName");
            return (Criteria) this;
        }

        public Criteria andBeanNameLessThan(String value) {
            addCriterion("`bean_name` <", value, "beanName");
            return (Criteria) this;
        }

        public Criteria andBeanNameLessThanOrEqualTo(String value) {
            addCriterion("`bean_name` <=", value, "beanName");
            return (Criteria) this;
        }

        public Criteria andBeanNameLike(String value) {
            addCriterion("`bean_name` like", value, "beanName");
            return (Criteria) this;
        }

        public Criteria andBeanNameNotLike(String value) {
            addCriterion("`bean_name` not like", value, "beanName");
            return (Criteria) this;
        }

        public Criteria andBeanNameIn(List<String> values) {
            addCriterion("`bean_name` in", values, "beanName");
            return (Criteria) this;
        }

        public Criteria andBeanNameNotIn(List<String> values) {
            addCriterion("`bean_name` not in", values, "beanName");
            return (Criteria) this;
        }

        public Criteria andBeanNameBetween(String value1, String value2) {
            addCriterion("`bean_name` between", value1, value2, "beanName");
            return (Criteria) this;
        }

        public Criteria andBeanNameNotBetween(String value1, String value2) {
            addCriterion("`bean_name` not between", value1, value2, "beanName");
            return (Criteria) this;
        }

        public Criteria andFactsIsNull() {
            addCriterion("`facts` is null");
            return (Criteria) this;
        }

        public Criteria andFactsIsNotNull() {
            addCriterion("`facts` is not null");
            return (Criteria) this;
        }

        public Criteria andFactsEqualTo(String value) {
            addCriterion("`facts` =", value, "facts");
            return (Criteria) this;
        }

        public Criteria andFactsNotEqualTo(String value) {
            addCriterion("`facts` <>", value, "facts");
            return (Criteria) this;
        }

        public Criteria andFactsGreaterThan(String value) {
            addCriterion("`facts` >", value, "facts");
            return (Criteria) this;
        }

        public Criteria andFactsGreaterThanOrEqualTo(String value) {
            addCriterion("`facts` >=", value, "facts");
            return (Criteria) this;
        }

        public Criteria andFactsLessThan(String value) {
            addCriterion("`facts` <", value, "facts");
            return (Criteria) this;
        }

        public Criteria andFactsLessThanOrEqualTo(String value) {
            addCriterion("`facts` <=", value, "facts");
            return (Criteria) this;
        }

        public Criteria andFactsLike(String value) {
            addCriterion("`facts` like", value, "facts");
            return (Criteria) this;
        }

        public Criteria andFactsNotLike(String value) {
            addCriterion("`facts` not like", value, "facts");
            return (Criteria) this;
        }

        public Criteria andFactsIn(List<String> values) {
            addCriterion("`facts` in", values, "facts");
            return (Criteria) this;
        }

        public Criteria andFactsNotIn(List<String> values) {
            addCriterion("`facts` not in", values, "facts");
            return (Criteria) this;
        }

        public Criteria andFactsBetween(String value1, String value2) {
            addCriterion("`facts` between", value1, value2, "facts");
            return (Criteria) this;
        }

        public Criteria andFactsNotBetween(String value1, String value2) {
            addCriterion("`facts` not between", value1, value2, "facts");
            return (Criteria) this;
        }

        public Criteria andParamIsNull() {
            addCriterion("`param` is null");
            return (Criteria) this;
        }

        public Criteria andParamIsNotNull() {
            addCriterion("`param` is not null");
            return (Criteria) this;
        }

        public Criteria andParamEqualTo(String value) {
            addCriterion("`param` =", value, "param");
            return (Criteria) this;
        }

        public Criteria andParamNotEqualTo(String value) {
            addCriterion("`param` <>", value, "param");
            return (Criteria) this;
        }

        public Criteria andParamGreaterThan(String value) {
            addCriterion("`param` >", value, "param");
            return (Criteria) this;
        }

        public Criteria andParamGreaterThanOrEqualTo(String value) {
            addCriterion("`param` >=", value, "param");
            return (Criteria) this;
        }

        public Criteria andParamLessThan(String value) {
            addCriterion("`param` <", value, "param");
            return (Criteria) this;
        }

        public Criteria andParamLessThanOrEqualTo(String value) {
            addCriterion("`param` <=", value, "param");
            return (Criteria) this;
        }

        public Criteria andParamLike(String value) {
            addCriterion("`param` like", value, "param");
            return (Criteria) this;
        }

        public Criteria andParamNotLike(String value) {
            addCriterion("`param` not like", value, "param");
            return (Criteria) this;
        }

        public Criteria andParamIn(List<String> values) {
            addCriterion("`param` in", values, "param");
            return (Criteria) this;
        }

        public Criteria andParamNotIn(List<String> values) {
            addCriterion("`param` not in", values, "param");
            return (Criteria) this;
        }

        public Criteria andParamBetween(String value1, String value2) {
            addCriterion("`param` between", value1, value2, "param");
            return (Criteria) this;
        }

        public Criteria andParamNotBetween(String value1, String value2) {
            addCriterion("`param` not between", value1, value2, "param");
            return (Criteria) this;
        }

        public Criteria andNodeIsNull() {
            addCriterion("`node` is null");
            return (Criteria) this;
        }

        public Criteria andNodeIsNotNull() {
            addCriterion("`node` is not null");
            return (Criteria) this;
        }

        public Criteria andNodeEqualTo(String value) {
            addCriterion("`node` =", value, "node");
            return (Criteria) this;
        }

        public Criteria andNodeNotEqualTo(String value) {
            addCriterion("`node` <>", value, "node");
            return (Criteria) this;
        }

        public Criteria andNodeGreaterThan(String value) {
            addCriterion("`node` >", value, "node");
            return (Criteria) this;
        }

        public Criteria andNodeGreaterThanOrEqualTo(String value) {
            addCriterion("`node` >=", value, "node");
            return (Criteria) this;
        }

        public Criteria andNodeLessThan(String value) {
            addCriterion("`node` <", value, "node");
            return (Criteria) this;
        }

        public Criteria andNodeLessThanOrEqualTo(String value) {
            addCriterion("`node` <=", value, "node");
            return (Criteria) this;
        }

        public Criteria andNodeLike(String value) {
            addCriterion("`node` like", value, "node");
            return (Criteria) this;
        }

        public Criteria andNodeNotLike(String value) {
            addCriterion("`node` not like", value, "node");
            return (Criteria) this;
        }

        public Criteria andNodeIn(List<String> values) {
            addCriterion("`node` in", values, "node");
            return (Criteria) this;
        }

        public Criteria andNodeNotIn(List<String> values) {
            addCriterion("`node` not in", values, "node");
            return (Criteria) this;
        }

        public Criteria andNodeBetween(String value1, String value2) {
            addCriterion("`node` between", value1, value2, "node");
            return (Criteria) this;
        }

        public Criteria andNodeNotBetween(String value1, String value2) {
            addCriterion("`node` not between", value1, value2, "node");
            return (Criteria) this;
        }

        public Criteria andOrderNumberIsNull() {
            addCriterion("`order_number` is null");
            return (Criteria) this;
        }

        public Criteria andOrderNumberIsNotNull() {
            addCriterion("`order_number` is not null");
            return (Criteria) this;
        }

        public Criteria andOrderNumberEqualTo(Integer value) {
            addCriterion("`order_number` =", value, "orderNumber");
            return (Criteria) this;
        }

        public Criteria andOrderNumberNotEqualTo(Integer value) {
            addCriterion("`order_number` <>", value, "orderNumber");
            return (Criteria) this;
        }

        public Criteria andOrderNumberGreaterThan(Integer value) {
            addCriterion("`order_number` >", value, "orderNumber");
            return (Criteria) this;
        }

        public Criteria andOrderNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("`order_number` >=", value, "orderNumber");
            return (Criteria) this;
        }

        public Criteria andOrderNumberLessThan(Integer value) {
            addCriterion("`order_number` <", value, "orderNumber");
            return (Criteria) this;
        }

        public Criteria andOrderNumberLessThanOrEqualTo(Integer value) {
            addCriterion("`order_number` <=", value, "orderNumber");
            return (Criteria) this;
        }

        public Criteria andOrderNumberIn(List<Integer> values) {
            addCriterion("`order_number` in", values, "orderNumber");
            return (Criteria) this;
        }

        public Criteria andOrderNumberNotIn(List<Integer> values) {
            addCriterion("`order_number` not in", values, "orderNumber");
            return (Criteria) this;
        }

        public Criteria andOrderNumberBetween(Integer value1, Integer value2) {
            addCriterion("`order_number` between", value1, value2, "orderNumber");
            return (Criteria) this;
        }

        public Criteria andOrderNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("`order_number` not between", value1, value2, "orderNumber");
            return (Criteria) this;
        }

        public Criteria andHandledTimesIsNull() {
            addCriterion("`handled_times` is null");
            return (Criteria) this;
        }

        public Criteria andHandledTimesIsNotNull() {
            addCriterion("`handled_times` is not null");
            return (Criteria) this;
        }

        public Criteria andHandledTimesEqualTo(Integer value) {
            addCriterion("`handled_times` =", value, "handledTimes");
            return (Criteria) this;
        }

        public Criteria andHandledTimesNotEqualTo(Integer value) {
            addCriterion("`handled_times` <>", value, "handledTimes");
            return (Criteria) this;
        }

        public Criteria andHandledTimesGreaterThan(Integer value) {
            addCriterion("`handled_times` >", value, "handledTimes");
            return (Criteria) this;
        }

        public Criteria andHandledTimesGreaterThanOrEqualTo(Integer value) {
            addCriterion("`handled_times` >=", value, "handledTimes");
            return (Criteria) this;
        }

        public Criteria andHandledTimesLessThan(Integer value) {
            addCriterion("`handled_times` <", value, "handledTimes");
            return (Criteria) this;
        }

        public Criteria andHandledTimesLessThanOrEqualTo(Integer value) {
            addCriterion("`handled_times` <=", value, "handledTimes");
            return (Criteria) this;
        }

        public Criteria andHandledTimesIn(List<Integer> values) {
            addCriterion("`handled_times` in", values, "handledTimes");
            return (Criteria) this;
        }

        public Criteria andHandledTimesNotIn(List<Integer> values) {
            addCriterion("`handled_times` not in", values, "handledTimes");
            return (Criteria) this;
        }

        public Criteria andHandledTimesBetween(Integer value1, Integer value2) {
            addCriterion("`handled_times` between", value1, value2, "handledTimes");
            return (Criteria) this;
        }

        public Criteria andHandledTimesNotBetween(Integer value1, Integer value2) {
            addCriterion("`handled_times` not between", value1, value2, "handledTimes");
            return (Criteria) this;
        }

        public Criteria andLastHandleMsgIsNull() {
            addCriterion("`last_handle_msg` is null");
            return (Criteria) this;
        }

        public Criteria andLastHandleMsgIsNotNull() {
            addCriterion("`last_handle_msg` is not null");
            return (Criteria) this;
        }

        public Criteria andLastHandleMsgEqualTo(String value) {
            addCriterion("`last_handle_msg` =", value, "lastHandleMsg");
            return (Criteria) this;
        }

        public Criteria andLastHandleMsgNotEqualTo(String value) {
            addCriterion("`last_handle_msg` <>", value, "lastHandleMsg");
            return (Criteria) this;
        }

        public Criteria andLastHandleMsgGreaterThan(String value) {
            addCriterion("`last_handle_msg` >", value, "lastHandleMsg");
            return (Criteria) this;
        }

        public Criteria andLastHandleMsgGreaterThanOrEqualTo(String value) {
            addCriterion("`last_handle_msg` >=", value, "lastHandleMsg");
            return (Criteria) this;
        }

        public Criteria andLastHandleMsgLessThan(String value) {
            addCriterion("`last_handle_msg` <", value, "lastHandleMsg");
            return (Criteria) this;
        }

        public Criteria andLastHandleMsgLessThanOrEqualTo(String value) {
            addCriterion("`last_handle_msg` <=", value, "lastHandleMsg");
            return (Criteria) this;
        }

        public Criteria andLastHandleMsgLike(String value) {
            addCriterion("`last_handle_msg` like", value, "lastHandleMsg");
            return (Criteria) this;
        }

        public Criteria andLastHandleMsgNotLike(String value) {
            addCriterion("`last_handle_msg` not like", value, "lastHandleMsg");
            return (Criteria) this;
        }

        public Criteria andLastHandleMsgIn(List<String> values) {
            addCriterion("`last_handle_msg` in", values, "lastHandleMsg");
            return (Criteria) this;
        }

        public Criteria andLastHandleMsgNotIn(List<String> values) {
            addCriterion("`last_handle_msg` not in", values, "lastHandleMsg");
            return (Criteria) this;
        }

        public Criteria andLastHandleMsgBetween(String value1, String value2) {
            addCriterion("`last_handle_msg` between", value1, value2, "lastHandleMsg");
            return (Criteria) this;
        }

        public Criteria andLastHandleMsgNotBetween(String value1, String value2) {
            addCriterion("`last_handle_msg` not between", value1, value2, "lastHandleMsg");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNull() {
            addCriterion("`created_at` is null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNotNull() {
            addCriterion("`created_at` is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtEqualTo(Date value) {
            addCriterion("`created_at` =", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotEqualTo(Date value) {
            addCriterion("`created_at` <>", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThan(Date value) {
            addCriterion("`created_at` >", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("`created_at` >=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThan(Date value) {
            addCriterion("`created_at` <", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThanOrEqualTo(Date value) {
            addCriterion("`created_at` <=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIn(List<Date> values) {
            addCriterion("`created_at` in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotIn(List<Date> values) {
            addCriterion("`created_at` not in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtBetween(Date value1, Date value2) {
            addCriterion("`created_at` between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotBetween(Date value1, Date value2) {
            addCriterion("`created_at` not between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIsNull() {
            addCriterion("`updated_at` is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIsNotNull() {
            addCriterion("`updated_at` is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtEqualTo(Date value) {
            addCriterion("`updated_at` =", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotEqualTo(Date value) {
            addCriterion("`updated_at` <>", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtGreaterThan(Date value) {
            addCriterion("`updated_at` >", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("`updated_at` >=", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtLessThan(Date value) {
            addCriterion("`updated_at` <", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtLessThanOrEqualTo(Date value) {
            addCriterion("`updated_at` <=", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIn(List<Date> values) {
            addCriterion("`updated_at` in", values, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotIn(List<Date> values) {
            addCriterion("`updated_at` not in", values, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtBetween(Date value1, Date value2) {
            addCriterion("`updated_at` between", value1, value2, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotBetween(Date value1, Date value2) {
            addCriterion("`updated_at` not between", value1, value2, "updatedAt");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bf_process_info
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bf_process_info
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}