package tk.mybatis.springboot.model;

import java.util.Date;

public class CreditInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_info.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_info.uid
     *
     * @mbggenerated
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_info.channel
     *
     * @mbggenerated
     */
    private String channel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_info.cert_no
     *
     * @mbggenerated
     */
    private String certNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_info.credit_no
     *
     * @mbggenerated
     */
    private String creditNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_info.credit_status
     *
     * @mbggenerated
     */
    private String creditStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_info.credit_limit
     *
     * @mbggenerated
     */
    private Integer creditLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_info.credit_available_limit
     *
     * @mbggenerated
     */
    private Integer creditAvailableLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_info.bank_account_no
     *
     * @mbggenerated
     */
    private String bankAccountNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_info.rsv1
     *
     * @mbggenerated
     */
    private String rsv1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_info.rsv2
     *
     * @mbggenerated
     */
    private String rsv2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_info.rsv3
     *
     * @mbggenerated
     */
    private String rsv3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_info.credit_at
     *
     * @mbggenerated
     */
    private Date creditAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_info.created_at
     *
     * @mbggenerated
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_info.updated_at
     *
     * @mbggenerated
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_info.id
     *
     * @return the value of credit_info.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_info.id
     *
     * @param id the value for credit_info.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_info.uid
     *
     * @return the value of credit_info.uid
     *
     * @mbggenerated
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_info.uid
     *
     * @param uid the value for credit_info.uid
     *
     * @mbggenerated
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_info.channel
     *
     * @return the value of credit_info.channel
     *
     * @mbggenerated
     */
    public String getChannel() {
        return channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_info.channel
     *
     * @param channel the value for credit_info.channel
     *
     * @mbggenerated
     */
    public void setChannel(String channel) {
        this.channel = channel == null ? null : channel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_info.cert_no
     *
     * @return the value of credit_info.cert_no
     *
     * @mbggenerated
     */
    public String getCertNo() {
        return certNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_info.cert_no
     *
     * @param certNo the value for credit_info.cert_no
     *
     * @mbggenerated
     */
    public void setCertNo(String certNo) {
        this.certNo = certNo == null ? null : certNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_info.credit_no
     *
     * @return the value of credit_info.credit_no
     *
     * @mbggenerated
     */
    public String getCreditNo() {
        return creditNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_info.credit_no
     *
     * @param creditNo the value for credit_info.credit_no
     *
     * @mbggenerated
     */
    public void setCreditNo(String creditNo) {
        this.creditNo = creditNo == null ? null : creditNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_info.credit_status
     *
     * @return the value of credit_info.credit_status
     *
     * @mbggenerated
     */
    public String getCreditStatus() {
        return creditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_info.credit_status
     *
     * @param creditStatus the value for credit_info.credit_status
     *
     * @mbggenerated
     */
    public void setCreditStatus(String creditStatus) {
        this.creditStatus = creditStatus == null ? null : creditStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_info.credit_limit
     *
     * @return the value of credit_info.credit_limit
     *
     * @mbggenerated
     */
    public Integer getCreditLimit() {
        return creditLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_info.credit_limit
     *
     * @param creditLimit the value for credit_info.credit_limit
     *
     * @mbggenerated
     */
    public void setCreditLimit(Integer creditLimit) {
        this.creditLimit = creditLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_info.credit_available_limit
     *
     * @return the value of credit_info.credit_available_limit
     *
     * @mbggenerated
     */
    public Integer getCreditAvailableLimit() {
        return creditAvailableLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_info.credit_available_limit
     *
     * @param creditAvailableLimit the value for credit_info.credit_available_limit
     *
     * @mbggenerated
     */
    public void setCreditAvailableLimit(Integer creditAvailableLimit) {
        this.creditAvailableLimit = creditAvailableLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_info.bank_account_no
     *
     * @return the value of credit_info.bank_account_no
     *
     * @mbggenerated
     */
    public String getBankAccountNo() {
        return bankAccountNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_info.bank_account_no
     *
     * @param bankAccountNo the value for credit_info.bank_account_no
     *
     * @mbggenerated
     */
    public void setBankAccountNo(String bankAccountNo) {
        this.bankAccountNo = bankAccountNo == null ? null : bankAccountNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_info.rsv1
     *
     * @return the value of credit_info.rsv1
     *
     * @mbggenerated
     */
    public String getRsv1() {
        return rsv1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_info.rsv1
     *
     * @param rsv1 the value for credit_info.rsv1
     *
     * @mbggenerated
     */
    public void setRsv1(String rsv1) {
        this.rsv1 = rsv1 == null ? null : rsv1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_info.rsv2
     *
     * @return the value of credit_info.rsv2
     *
     * @mbggenerated
     */
    public String getRsv2() {
        return rsv2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_info.rsv2
     *
     * @param rsv2 the value for credit_info.rsv2
     *
     * @mbggenerated
     */
    public void setRsv2(String rsv2) {
        this.rsv2 = rsv2 == null ? null : rsv2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_info.rsv3
     *
     * @return the value of credit_info.rsv3
     *
     * @mbggenerated
     */
    public String getRsv3() {
        return rsv3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_info.rsv3
     *
     * @param rsv3 the value for credit_info.rsv3
     *
     * @mbggenerated
     */
    public void setRsv3(String rsv3) {
        this.rsv3 = rsv3 == null ? null : rsv3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_info.credit_at
     *
     * @return the value of credit_info.credit_at
     *
     * @mbggenerated
     */
    public Date getCreditAt() {
        return creditAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_info.credit_at
     *
     * @param creditAt the value for credit_info.credit_at
     *
     * @mbggenerated
     */
    public void setCreditAt(Date creditAt) {
        this.creditAt = creditAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_info.created_at
     *
     * @return the value of credit_info.created_at
     *
     * @mbggenerated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_info.created_at
     *
     * @param createdAt the value for credit_info.created_at
     *
     * @mbggenerated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_info.updated_at
     *
     * @return the value of credit_info.updated_at
     *
     * @mbggenerated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_info.updated_at
     *
     * @param updatedAt the value for credit_info.updated_at
     *
     * @mbggenerated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}