package tk.mybatis.springboot.model;

public class CreditInfoWithBLOBs extends CreditInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_info.request_info
     *
     * @mbggenerated
     */
    private String requestInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_info.response_info
     *
     * @mbggenerated
     */
    private String responseInfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_info.request_info
     *
     * @return the value of credit_info.request_info
     *
     * @mbggenerated
     */
    public String getRequestInfo() {
        return requestInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_info.request_info
     *
     * @param requestInfo the value for credit_info.request_info
     *
     * @mbggenerated
     */
    public void setRequestInfo(String requestInfo) {
        this.requestInfo = requestInfo == null ? null : requestInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_info.response_info
     *
     * @return the value of credit_info.response_info
     *
     * @mbggenerated
     */
    public String getResponseInfo() {
        return responseInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_info.response_info
     *
     * @param responseInfo the value for credit_info.response_info
     *
     * @mbggenerated
     */
    public void setResponseInfo(String responseInfo) {
        this.responseInfo = responseInfo == null ? null : responseInfo.trim();
    }
}