package tk.mybatis.springboot.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import tk.mybatis.springboot.model.BfProcessInfo;
import tk.mybatis.springboot.model.BfProcessInfoExample;

public interface BfProcessInfoMapper {
    @Select("select count(1) from aibankfund.bf_process_info where exec_status = 'SUCCESS' and updated_at < curdate() - interval 1 month ;\n")
    int selectData();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bf_process_info
     *
     * @mbggenerated
     */
    int countByExample(BfProcessInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bf_process_info
     *
     * @mbggenerated
     */
    int deleteByExample(BfProcessInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bf_process_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bf_process_info
     *
     * @mbggenerated
     */
    int insert(BfProcessInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bf_process_info
     *
     * @mbggenerated
     */
    int insertSelective(BfProcessInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bf_process_info
     *
     * @mbggenerated
     */
    List<BfProcessInfo> selectByExample(BfProcessInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bf_process_info
     *
     * @mbggenerated
     */
    BfProcessInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bf_process_info
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BfProcessInfo record, @Param("example") BfProcessInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bf_process_info
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BfProcessInfo record, @Param("example") BfProcessInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bf_process_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BfProcessInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bf_process_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BfProcessInfo record);
}