package tk.mybatis.springboot.mapper;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.json.JSONObject;
import org.springframework.stereotype.Service;
import tk.mybatis.springboot.model.CreditInfo;
import tk.mybatis.springboot.model.CreditInfoExample;
import tk.mybatis.springboot.model.CreditInfoWithBLOBs;
public interface CreditInfoMapper {

    @Select("select response_info from credit_info where uid = #{uid,jdbcType=VARCHAR} and channel = #{channel,jdbcType=VARCHAR}")
    String selectCreditInfo(@Param("uid") String uid, @Param("channel") String channel);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_info
     *
     * @mbggenerated
     */
    int countByExample(CreditInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_info
     *
     * @mbggenerated
     */
    int deleteByExample(CreditInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_info
     *
     * @mbggenerated
     */
    int insert(CreditInfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_info
     *
     * @mbggenerated
     */
    int insertSelective(CreditInfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_info
     *
     * @mbggenerated
     */
    List<CreditInfoWithBLOBs> selectByExampleWithBLOBs(CreditInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_info
     *
     * @mbggenerated
     */
    List<CreditInfo> selectByExample(CreditInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_info
     *
     * @mbggenerated
     */
    CreditInfoWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_info
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CreditInfoWithBLOBs record, @Param("example") CreditInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_info
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") CreditInfoWithBLOBs record, @Param("example") CreditInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_info
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CreditInfo record, @Param("example") CreditInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CreditInfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(CreditInfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CreditInfo record);
}